### ISSUE TITLE
Update course links on website (2 locations)

### ISSUE THREAD

**Issue by dlkessler** [UWRealityLab/website#38]
Please update the links on all the courses, both the links from the landing page (realitylab.uw.edu) and from the courses page (realitylab.uw.edu/courses.html).  Some of the classes there currently link to the 2018 or 2017 versions of themselves, instead of the 2019 versions.

And in September, please ask me for information on new courses, such as the Build Your Own VR Headset class that Doug Lanman will teach in Winter Quarter.  Course code will probably CSE 490

**Comment by kimalexj** [comment]
Hello! As of now this issue is for the most part addressed aside from a few things that I wanted your input on:
1. CSE 558 I believe does not have a specific course linked to it, how should I address this?
2. CSE 576 does not have any updates to a 2019 page at least from my searching.
3. The '19 autumn pages have not been built yet, should I continue to use these links anyway?

**Comment by dlkessler** [comment]
Thanks!  As a rule of thumb, update courses to the most recent version of them available - if there isn't a 2020 version, update to the 2019 version, if no 2019 then use the 2018. 
We can do this again as updates become relevant, but for now it was embarrassingly out of date.

**Comment by dlkessler** [comment]
Please push to live whatever updates you've done on this item, and push any future updates to live as well - this is a simple one that doesn't need review from me unless you have questions.
